name: Build KubeTaint  

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install requests
        pip install pandas
        pip install PyYAML
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run integration and taint-related tests 
      run: |
        python TEST_PARSING.py  